backend:
  name: git-gateway
  branch: master
media_library:
  name: cloudinary
  output_filename_only: false
  use_transformations: false
  use_secure_url: true
  config:
    cloud_name: dz8vyplpm
    api_key: 519588533491653
i18n:
  structure: multiple_folders
  locales: [ja, en]
collections:
  - name: photos
    label: Photos
    folder: "src/content/photos"
    slug: "{{year}}-{{month}}-{{day}}_{{title}}"
    summary: "{{title}} - Age: {{age}} Author: {{commit_author}}"
    i18n: true
    create: true
    delete: true
    fields:
      - { name: "title", widget: "string", label: "Title", i18n: true }
      - { name: "photo", widget: "image", label: "Photo", i18n: "duplicate", media_library: { name: cloudinary } }
      - { name: "caption", widget: "text", label: "Caption", i18n: true }
      - { name: "publish-date", widget: "datetime", label: Publish Date, i18n: "duplicate" }
      - name: "age"
        widget: "select"
        label: "Age"
        options:
          - { label: "Before Birth", value: "album.before_birth" }
          - { label: "A few days old", value: "album.few_days_old" }
          - { label: "A few weeks old", value: "album.few_weeks_old" }
          - { label: "1 Month Old", value: "album.1_month_old" }
          - { label: "2 Months Old", value: "album.2_months_old" }
          - { label: "3 Months Old", value: "album.3_months_old" }
          - { label: "4 Months Old", value: "album.4_months_old" }
          - { label: "5 Months Old", value: "album.5_months_old" }
          - { label: "6 Months Old", value: "album.6_months_old" } 
        default: "Before Birth"
        i18n: "duplicate"
      - { name: "tags", widget: "list", label: "Tags", i18n: true }