backend:
  name: git-gateway
  branch: master
media_library:
  name: cloudinary
  output_filename_only: false
  use_transformations: false
  use_secure_url: true
  config:
    cloud_name: dz8vyplpm
    api_key: 519588533491653
i18n:
  structure: multiple_folders
  locales: [ja, en]
collections:
  - name: photos
    label: Photos
    folder: "src/content/photos"
    slug: "{{year}}-{{month}}-{{day}}_{{title}}"
    summary: "{{title}} - Age: {{age}} Author: {{commit_author}}"
    i18n: true
    create: true
    delete: true
    fields:
      - { name: "title", widget: "string", label: "Title", i18n: true }
      - { name: "photo", widget: "image", label: "Photo", i18n: "duplicate", media_library: { name: cloudinary } }
      - { name: "caption", widget: "text", label: "Caption", i18n: true }
      - { name: "publish-date", widget: "datetime", label: Publish Date, i18n: "duplicate" }
      - { name: "age", widget: "select", label: "Age", options: ["Before Birth", "A few days old", "A few weeks old", "1 Month Old", "2 Months Old", "3 Months Old", "4 Months Old", "5 Months Old", "6 Months Old"], default: "Before Birth", i18n: "duplicate" }
      - { name: "tags", widget: "list", label: "Tags", i18n: true }